services:
  postgres:
    image: postgis/postgis:16-3.4 # PostGIS 포함 이미지 사용
    container_name: livelihoodCoupon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-livelihoodCoupon_db}
      POSTGRES_USER: ${POSTGRES_USER:-livelihoodCoupon_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-livelihoodCoupon_password}
      TZ: Asia/Seoul
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped
    networks:
      - livelihoodCoupon-net

  redis:
    image: redis:7.4-alpine
    container_name: livelihoodCoupon-redis
    command: [ "sh", "-c", "exec redis-server --appendonly ${REDIS_AOF:-yes}" ]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    networks:
      - livelihoodCoupon-net

volumes:
  postgres_data:
  redis_data:

networks:
  livelihoodCoupon-net:
    external: true # This network is defined in the main infra/docker-compose.yml